FROM openjdk:17-jdk-alpine
ARG JAR_FILE=target/*.jar
RUN mkdir /opt/eureka-server
COPY ${JAR_FILE} /opt/eureka-server/eurekaserver.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/opt/eureka-server/eurekaserver.jar"]


