FROM openjdk:17-jdk-alpine
ARG JAR_FILE=target/*.jar
RUN mkdir /opt/car-service
COPY ${JAR_FILE} /opt/car-service/carservice.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/opt/car-service/carservice.jar"]


