server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/Enrique-MCPP/keycloak.git
          search-paths: config-data
          clone-on-start: true
  application:
    name: config-service


